export declare const WS_EVENTS: {
    WS_SEND: string;
    WS_RECEIVE: string;
    ERROR: string;
    AUTH_OK: string;
    AUTH_FAIL: string;
    FILE_REQUEST: string;
    FILE_STORED: string;
    FILE_STORE_ERROR: string;
    CALL_DISCONNECTED: string;
    PING: string;
    RECONNECT: string;
    WS_PING: string;
    WS_PONG: string;
};
export declare const APP_EVENTS: {
    AUTH_FAIL: string;
    BOT_ERROR: string;
    DISCONNECTED: string;
    FILE_REQUEST: string;
    FILE_STORED: string;
    FILE_STORE_ERROR: string;
    CONNECTED: string;
    RECORDING_FAILED: string;
    RECORDING_COMPLETE: string;
    RECORDING_SESSION_NOT_FOUND: string;
    CALL_DISCONNECTED: string;
    PLAYBACK_FINISHED: string;
    SPEECH_RECOGNITION_TIMEOUT: string;
    TRANSCRIBE: string;
    VARIABLES_SET: string;
    VARIABLES_DELETE: string;
    VARIABLES_GET: string;
};
export declare const WS_CALL_EVENTS: {
    BOT_ERROR: string;
    RECORDING_SESSION_NOT_FOUND: string;
    RECORDING_FAILED: string;
    RECORDING_COMPLETE: string;
    TRANSCRIBE: string;
    SPEECH_RECOGNITION_TIMEOUT: string;
    PLAYBACK_FINISHED: string;
    CALL_DISCONNECTED: string;
    VARIABLES_SET: string;
    VARIABLES_DELETE: string;
    VARIABLES_GET: string;
};
